# define data-split - folds for 6-fold cross validation
train:
    fold1:
        - 4687
        - 4693
        - 4695
        - 4697
        - 4709
        - 4750
        - 5013
        - 5014
        - 5015

    fold2:
        - 4811
        - 4816
        - 4852
        - 4859
        - 4863
        - 4864
        - 5017
        - 5032
        - 5051
        - 5057

    fold3:
        - 4874
        - 4888
        - 4899
        - 4906
        - 4923
        - 4924
        - 5058
        - 5063
        - 5072
        - 5104

    fold4:
        - 4927
        - 4939
        - 4999
        - 5004
        - 5006
        - 5011
        - 5261
        - 5300
        - 5301
        - 5303

    fold5:
        - 5304
        - 5305
        - 5309
        - 5311
        - 5314
        - 5315
        - 5316
        - 5317
        - 5319
        - 5329

    fold6:
        - 5331
        - 5334
        - 5335
        - 5340

test:
    - 5016
    - 5032
    - 5063
    - 5304
    - 5311
    - 5319
    - 5329
    - 5334
    - 5340
